{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iubenda",
    "module": "mobile-sdk",
    "version": "2.9.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mobile-sdk-2.9.8.aar",
          "url": "mobile-sdk-2.9.8.aar",
          "size": 105710,
          "sha512": "a44532af6e1baedec64aaea4da5b9aa7c4fce6cf974f543e4c6d37a7d4c5e8f836fc75fa26500dbdbf82e38df86bc9c5407f26871beac5c0673825aaddf2930f",
          "sha256": "5d4540edfd614f2ecb48243d14cacb68acd39bd137a6640ab349a4faade292a1",
          "sha1": "b8a843c5dee5b540f1c6227f703ce30756a3fe04",
          "md5": "80568143f90d069cc9bcc5f38e4f8633"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-2.9.8.aar",
          "url": "mobile-sdk-2.9.8.aar",
          "size": 105710,
          "sha512": "a44532af6e1baedec64aaea4da5b9aa7c4fce6cf974f543e4c6d37a7d4c5e8f836fc75fa26500dbdbf82e38df86bc9c5407f26871beac5c0673825aaddf2930f",
          "sha256": "5d4540edfd614f2ecb48243d14cacb68acd39bd137a6640ab349a4faade292a1",
          "sha1": "b8a843c5dee5b540f1c6227f703ce30756a3fe04",
          "md5": "80568143f90d069cc9bcc5f38e4f8633"
        }
      ]
    }
  ]
}
