{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iubenda",
    "module": "mobile-sdk",
    "version": "2.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mobile-sdk-2.7.1.aar",
          "url": "mobile-sdk-2.7.1.aar",
          "size": 89665,
          "sha512": "8e75ce99b5ab7c5eabb60502b7ac41ee46d158a4b733492550c24d490bb9102031c8a4f07329703a06d5febb2076870a615c0081f27b8b5aa42046d14ef12afc",
          "sha256": "59e96e15117f9cb05603d56dfce124102d6146829bbe6f53fe152a417675c473",
          "sha1": "9163465479241244d196c29a60ed6368059fd2a0",
          "md5": "d503327c17f26ae7ff7444803c8b4863"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-2.7.1.aar",
          "url": "mobile-sdk-2.7.1.aar",
          "size": 89665,
          "sha512": "8e75ce99b5ab7c5eabb60502b7ac41ee46d158a4b733492550c24d490bb9102031c8a4f07329703a06d5febb2076870a615c0081f27b8b5aa42046d14ef12afc",
          "sha256": "59e96e15117f9cb05603d56dfce124102d6146829bbe6f53fe152a417675c473",
          "sha1": "9163465479241244d196c29a60ed6368059fd2a0",
          "md5": "d503327c17f26ae7ff7444803c8b4863"
        }
      ]
    }
  ]
}
