{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iubenda",
    "module": "mobile-sdk",
    "version": "2.9.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mobile-sdk-2.9.5.aar",
          "url": "mobile-sdk-2.9.5.aar",
          "size": 105640,
          "sha512": "54ead0e19d99134b32a9067117ea994c2ed27a13e3d2fbaa799f94314f3992b2b1e315ea6e49baab6d7efb848640c6e170e97389e5afbce0e8f9f1f96ce40dd4",
          "sha256": "13fecdc8d399ba4972806e995cd4c4d65ffee6c90046b224578e0e5043de7c5f",
          "sha1": "bf29d3af1cf093fb84eb6831b6a3e3cb6324f826",
          "md5": "91c9253d4a47f25bc12918e4e3c798ee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-2.9.5.aar",
          "url": "mobile-sdk-2.9.5.aar",
          "size": 105640,
          "sha512": "54ead0e19d99134b32a9067117ea994c2ed27a13e3d2fbaa799f94314f3992b2b1e315ea6e49baab6d7efb848640c6e170e97389e5afbce0e8f9f1f96ce40dd4",
          "sha256": "13fecdc8d399ba4972806e995cd4c4d65ffee6c90046b224578e0e5043de7c5f",
          "sha1": "bf29d3af1cf093fb84eb6831b6a3e3cb6324f826",
          "md5": "91c9253d4a47f25bc12918e4e3c798ee"
        }
      ]
    }
  ]
}
