{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iubenda",
    "module": "mobile-sdk",
    "version": "2.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "6q3anrtkezhejnhxosfbsualli"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mobile-sdk-2.3.5.aar",
          "url": "mobile-sdk-2.3.5.aar",
          "size": 63227,
          "sha512": "399476494c69658f47566caea6969127d499d081a6cc6b661cebf22ad2cbd1df0b048f9237ebb6beeff0f09aaff23bfc17a2dcf9c77ef0fc079d7459549dd2ad",
          "sha256": "3ea28937bba3edda6dc898af9c16f27794c22d892c1e463310749f504f9f79d2",
          "sha1": "7de07c232081003b79ba2e26a9e3081cffb50ee1",
          "md5": "8bbfcb9a7ef5bcfb1715a717b267f31a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-2.3.5.aar",
          "url": "mobile-sdk-2.3.5.aar",
          "size": 63227,
          "sha512": "399476494c69658f47566caea6969127d499d081a6cc6b661cebf22ad2cbd1df0b048f9237ebb6beeff0f09aaff23bfc17a2dcf9c77ef0fc079d7459549dd2ad",
          "sha256": "3ea28937bba3edda6dc898af9c16f27794c22d892c1e463310749f504f9f79d2",
          "sha1": "7de07c232081003b79ba2e26a9e3081cffb50ee1",
          "md5": "8bbfcb9a7ef5bcfb1715a717b267f31a"
        }
      ]
    }
  ]
}
