{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iubenda",
    "module": "mobile-sdk",
    "version": "2.5.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "xpxqpksyqramrntwqx6pu6kjq4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mobile-sdk-2.5.9.aar",
          "url": "mobile-sdk-2.5.9.aar",
          "size": 69113,
          "sha512": "6937f982189c4b9142badfebbfe6e309c04de2547788c9eaa55b83140f1cf4d106d97c001d564b96ca8b2c1ea4906e61edb6e8d733cab7e7377c247c1e73cc78",
          "sha256": "0a5929ccac8bb1c13c154a40e56d4349d1b6cd4bcd72088a88f075fd34cc9567",
          "sha1": "81eb915dde18243b1338e3f60c1967a5204b6a88",
          "md5": "427ff59db40c255f1aafce5cb8c29f14"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-2.5.9.aar",
          "url": "mobile-sdk-2.5.9.aar",
          "size": 69113,
          "sha512": "6937f982189c4b9142badfebbfe6e309c04de2547788c9eaa55b83140f1cf4d106d97c001d564b96ca8b2c1ea4906e61edb6e8d733cab7e7377c247c1e73cc78",
          "sha256": "0a5929ccac8bb1c13c154a40e56d4349d1b6cd4bcd72088a88f075fd34cc9567",
          "sha1": "81eb915dde18243b1338e3f60c1967a5204b6a88",
          "md5": "427ff59db40c255f1aafce5cb8c29f14"
        }
      ]
    }
  ]
}
