{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iubenda",
    "module": "mobile-sdk",
    "version": "2.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mobile-sdk-2.6.9.aar",
          "url": "mobile-sdk-2.6.9.aar",
          "size": 85189,
          "sha512": "f1109a38099da04687ae941dccdb52580b10a480fcccb7aa0c98cd2d033d189ea6bfe8b7e1abc288456e5da0d1c75f149e43caf3bd69b42ef7e6ce4438262311",
          "sha256": "aafff9ee003a7e24e31af7bf3506f3a19684e0f66153efa986be057d0a6d072a",
          "sha1": "417726e6355a9e50e05df10e38facf8a3168e364",
          "md5": "a0375c74d642d678e22c5f749031d832"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-2.6.9.aar",
          "url": "mobile-sdk-2.6.9.aar",
          "size": 85189,
          "sha512": "f1109a38099da04687ae941dccdb52580b10a480fcccb7aa0c98cd2d033d189ea6bfe8b7e1abc288456e5da0d1c75f149e43caf3bd69b42ef7e6ce4438262311",
          "sha256": "aafff9ee003a7e24e31af7bf3506f3a19684e0f66153efa986be057d0a6d072a",
          "sha1": "417726e6355a9e50e05df10e38facf8a3168e364",
          "md5": "a0375c74d642d678e22c5f749031d832"
        }
      ]
    }
  ]
}
