{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iubenda",
    "module": "mobile-sdk",
    "version": "2.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mobile-sdk-2.9.1.aar",
          "url": "mobile-sdk-2.9.1.aar",
          "size": 104467,
          "sha512": "41720dac2dd896036a39a67f86543a88996d07e85f6ebbbfd87a3b1fab63d61596a8b7a9271b58ffec62a860cfd67a3b14899c0516c94d9380236850021aa96b",
          "sha256": "9057ef76140b9f4ebb8ba5be2725a0d4c740af5ac9769ed151231e61559cdd2c",
          "sha1": "1b200e47f2f68ad4e1fc15723a1f52e8fbde1d56",
          "md5": "76b52e803bcfbfc19520fb713d88357d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-2.9.1.aar",
          "url": "mobile-sdk-2.9.1.aar",
          "size": 104467,
          "sha512": "41720dac2dd896036a39a67f86543a88996d07e85f6ebbbfd87a3b1fab63d61596a8b7a9271b58ffec62a860cfd67a3b14899c0516c94d9380236850021aa96b",
          "sha256": "9057ef76140b9f4ebb8ba5be2725a0d4c740af5ac9769ed151231e61559cdd2c",
          "sha1": "1b200e47f2f68ad4e1fc15723a1f52e8fbde1d56",
          "md5": "76b52e803bcfbfc19520fb713d88357d"
        }
      ]
    }
  ]
}
