{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iubenda",
    "module": "mobile-sdk",
    "version": "2.5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "yw3m4d4vobeitkprbu4pltznhy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mobile-sdk-2.5.5.aar",
          "url": "mobile-sdk-2.5.5.aar",
          "size": 65693,
          "sha512": "0acaef00cbf506ac147335eb93be7384906b8184df83d8eabed6fc5d06086a5df65b161e87ccea0300aac205eddacc48cc1f17f6ef68c0bc27bccfa6f4302d6f",
          "sha256": "ab15c078a0dff81546e3926e5912d45b45022db9cc0f2537df9132e1d37f2cfe",
          "sha1": "991effc60573800102f1e1e6b0b94484c14f89d6",
          "md5": "45b9f43bff4b4b0e22d12942dd8cfefd"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-2.5.5.aar",
          "url": "mobile-sdk-2.5.5.aar",
          "size": 65693,
          "sha512": "0acaef00cbf506ac147335eb93be7384906b8184df83d8eabed6fc5d06086a5df65b161e87ccea0300aac205eddacc48cc1f17f6ef68c0bc27bccfa6f4302d6f",
          "sha256": "ab15c078a0dff81546e3926e5912d45b45022db9cc0f2537df9132e1d37f2cfe",
          "sha1": "991effc60573800102f1e1e6b0b94484c14f89d6",
          "md5": "45b9f43bff4b4b0e22d12942dd8cfefd"
        }
      ]
    }
  ]
}
