{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iubenda",
    "module": "mobile-sdk",
    "version": "2.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "6upg5rjtl5albdoy6227rvxzhi"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mobile-sdk-2.6.1.aar",
          "url": "mobile-sdk-2.6.1.aar",
          "size": 70812,
          "sha512": "ff8df2d8eb83641c283d970237efdbdd29190c972a3b274383e716126de477926940a2adc9d38da3c1f286236c7795e182a0e74ddea55e30ce3a425bd9eacd2a",
          "sha256": "d29534a8e8377236508ea3687a4fdfd2da436161ace46c4eb19de2ccedcd136b",
          "sha1": "242dd32313be5c3c5d2a364dec2d70c2b7852d92",
          "md5": "eeeea8cf29fd5ec1ba8691fdb3d43f86"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-2.6.1.aar",
          "url": "mobile-sdk-2.6.1.aar",
          "size": 70812,
          "sha512": "ff8df2d8eb83641c283d970237efdbdd29190c972a3b274383e716126de477926940a2adc9d38da3c1f286236c7795e182a0e74ddea55e30ce3a425bd9eacd2a",
          "sha256": "d29534a8e8377236508ea3687a4fdfd2da436161ace46c4eb19de2ccedcd136b",
          "sha1": "242dd32313be5c3c5d2a364dec2d70c2b7852d92",
          "md5": "eeeea8cf29fd5ec1ba8691fdb3d43f86"
        }
      ]
    }
  ]
}
