{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iubenda",
    "module": "mobile-sdk",
    "version": "2.9.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mobile-sdk-2.9.7.aar",
          "url": "mobile-sdk-2.9.7.aar",
          "size": 105314,
          "sha512": "f96254da9788d4f2e2ec0fb69b067d7d77efcb7d081a972e77269c576c98b75b6b758bc9e2beaf5f8dce7c1f146fd86fe11dabef5789b31d0c3d26036bd76e04",
          "sha256": "747d12f7186146616c591ce7d0f5fba0447064ed6aeb3938b1ebb2e799341318",
          "sha1": "44279bf5250b1dc668a0cdb1ab3c80689bd9d8ba",
          "md5": "dcc77d161c242aa3f6043fce6a22822e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-2.9.7.aar",
          "url": "mobile-sdk-2.9.7.aar",
          "size": 105314,
          "sha512": "f96254da9788d4f2e2ec0fb69b067d7d77efcb7d081a972e77269c576c98b75b6b758bc9e2beaf5f8dce7c1f146fd86fe11dabef5789b31d0c3d26036bd76e04",
          "sha256": "747d12f7186146616c591ce7d0f5fba0447064ed6aeb3938b1ebb2e799341318",
          "sha1": "44279bf5250b1dc668a0cdb1ab3c80689bd9d8ba",
          "md5": "dcc77d161c242aa3f6043fce6a22822e"
        }
      ]
    }
  ]
}
