{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iubenda",
    "module": "mobile-sdk",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "zvflswgvnvaepjh7hmufn6vn7a"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mobile-sdk-2.3.0.aar",
          "url": "mobile-sdk-2.3.0.aar",
          "size": 59245,
          "sha512": "d6e4de50f163c8013723312d73ee7ef192b0ca58ba629812e03e29560ddf9dd9832454c8888115b49758d0f8af9acbc87eb9721b7c4226074c52b9a8f5502482",
          "sha256": "93e09ad37f6ad1dde4bb9e2b406447512334570658a24c5aa4b6a7e65e800ffa",
          "sha1": "f9ecf67a1cb74e92fc94f8618866cf16dd4373f3",
          "md5": "e229d0e625450046d3876242a814a0f7"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-2.3.0.aar",
          "url": "mobile-sdk-2.3.0.aar",
          "size": 59245,
          "sha512": "d6e4de50f163c8013723312d73ee7ef192b0ca58ba629812e03e29560ddf9dd9832454c8888115b49758d0f8af9acbc87eb9721b7c4226074c52b9a8f5502482",
          "sha256": "93e09ad37f6ad1dde4bb9e2b406447512334570658a24c5aa4b6a7e65e800ffa",
          "sha1": "f9ecf67a1cb74e92fc94f8618866cf16dd4373f3",
          "md5": "e229d0e625450046d3876242a814a0f7"
        }
      ]
    }
  ]
}
