{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iubenda",
    "module": "mobile-sdk",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "bqwkcbtn2bgozpjf6sbjtj2rha"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mobile-sdk-2.6.0.aar",
          "url": "mobile-sdk-2.6.0.aar",
          "size": 70815,
          "sha512": "315810933d94984c1a7350d9815be8a9884b6c28f2a24b5e0267684b2795f984ba03ab4aa38bb57844d62af64a0af71a4660200b732825af903d65e30ddcca83",
          "sha256": "e7a107bf86be3dfc4ea656abaf59ccc586598c796941f4f4f4ce66514d90e436",
          "sha1": "5a25c243cd2e014a17a66598c48b6cefc9f3bde1",
          "md5": "82662042b12e52e8161f71be13acda76"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-2.6.0.aar",
          "url": "mobile-sdk-2.6.0.aar",
          "size": 70815,
          "sha512": "315810933d94984c1a7350d9815be8a9884b6c28f2a24b5e0267684b2795f984ba03ab4aa38bb57844d62af64a0af71a4660200b732825af903d65e30ddcca83",
          "sha256": "e7a107bf86be3dfc4ea656abaf59ccc586598c796941f4f4f4ce66514d90e436",
          "sha1": "5a25c243cd2e014a17a66598c48b6cefc9f3bde1",
          "md5": "82662042b12e52e8161f71be13acda76"
        }
      ]
    }
  ]
}
