{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iubenda",
    "module": "mobile-sdk",
    "version": "2.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "2tv6rrs5jnbzle7oii52cr5eom"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mobile-sdk-2.6.2.aar",
          "url": "mobile-sdk-2.6.2.aar",
          "size": 83214,
          "sha512": "fe75453966563b53ed6ceb1dff795feb52e999fd4d8d476df04a2ce0bf35dae1f6cc9c03261b8f7a8719a36d729371d76d6156c7228781afc41de4e90daa708f",
          "sha256": "51b19e96291c651e29f6618a74c6a84098b6fcc358dcf1170f62a9454470f070",
          "sha1": "97fd11951ac58d20ede160a3b812fdb20352dc47",
          "md5": "587c20b7404c54f8cc93d0578d081484"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-2.6.2.aar",
          "url": "mobile-sdk-2.6.2.aar",
          "size": 83214,
          "sha512": "fe75453966563b53ed6ceb1dff795feb52e999fd4d8d476df04a2ce0bf35dae1f6cc9c03261b8f7a8719a36d729371d76d6156c7228781afc41de4e90daa708f",
          "sha256": "51b19e96291c651e29f6618a74c6a84098b6fcc358dcf1170f62a9454470f070",
          "sha1": "97fd11951ac58d20ede160a3b812fdb20352dc47",
          "md5": "587c20b7404c54f8cc93d0578d081484"
        }
      ]
    }
  ]
}
