{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iubenda",
    "module": "mobile-sdk",
    "version": "2.6.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "5zart6cdffbjddleddwkyfnbny"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mobile-sdk-2.6.3.aar",
          "url": "mobile-sdk-2.6.3.aar",
          "size": 83943,
          "sha512": "36f4b60a6cc4a13c4f39ec583aa31b9094677c23ba5562c42084fed032df300693fa360a6d77dd47c70f8ea44298cb51ad12b799e5ac4ae8f81c2a29c4c5dd5e",
          "sha256": "4bb05a10cbad35a7d3e4d18619e14301418ec501802f3283da3fb8c4878017a9",
          "sha1": "df2ff93ca9a3616b76b0ce23ba79a11cbfea1ed4",
          "md5": "dc908e38d36e70019bfb4c3d182f8a73"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-2.6.3.aar",
          "url": "mobile-sdk-2.6.3.aar",
          "size": 83943,
          "sha512": "36f4b60a6cc4a13c4f39ec583aa31b9094677c23ba5562c42084fed032df300693fa360a6d77dd47c70f8ea44298cb51ad12b799e5ac4ae8f81c2a29c4c5dd5e",
          "sha256": "4bb05a10cbad35a7d3e4d18619e14301418ec501802f3283da3fb8c4878017a9",
          "sha1": "df2ff93ca9a3616b76b0ce23ba79a11cbfea1ed4",
          "md5": "dc908e38d36e70019bfb4c3d182f8a73"
        }
      ]
    }
  ]
}
