{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iubenda",
    "module": "mobile-sdk",
    "version": "2.9.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mobile-sdk-2.9.6.aar",
          "url": "mobile-sdk-2.9.6.aar",
          "size": 105825,
          "sha512": "996b126f90d84524dce84ee458dd4ba17a79d583ffba9a75913314aac95676bcc658aa14e85f6bd2503bb4be7be2b433ed6d8a4530b14422b4f96eb296973103",
          "sha256": "a984318cc65271f6001caa10962c092081a5049b98a65761e4cef43300425576",
          "sha1": "0f6b04200602b00d6a998663fed40e763c5a94aa",
          "md5": "a0290411d466a3c01bf8cc848a1c60b2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-2.9.6.aar",
          "url": "mobile-sdk-2.9.6.aar",
          "size": 105825,
          "sha512": "996b126f90d84524dce84ee458dd4ba17a79d583ffba9a75913314aac95676bcc658aa14e85f6bd2503bb4be7be2b433ed6d8a4530b14422b4f96eb296973103",
          "sha256": "a984318cc65271f6001caa10962c092081a5049b98a65761e4cef43300425576",
          "sha1": "0f6b04200602b00d6a998663fed40e763c5a94aa",
          "md5": "a0290411d466a3c01bf8cc848a1c60b2"
        }
      ]
    }
  ]
}
